In [3]:
import numpy as np

In [162]:
# Esercizio 1 - Massima sottosequenza comune (Longest Common Subsequence, i.e., LCS)

def LCS(string1, string2):
    s = ' ' + string1 # Aggiungiamo il carattere vuoto sia a s sia a t
    t = ' ' + string2
    n = len(s)
    m = len(t)
    # Costruiamo una tabella n x m
    L = np.zeros((n, m)) # Modo 1 per inizializzare una matrice di tutti zeri

    for i in range(1,n):
        for j in range(1,m):
            if s[i] == t[j]: # Match
                L[i][j] = L[i-1][j-1] + 1
            else: # Consideriamo il massimo tra i risultati delle celle (i-1,j) e (i,j-1), che abbiamo già risolto
                L[i][j] = max(L[i-1][j], L[i][j-1]) 

    print("Tabella L: \n" + str(L))
    print("Lunghezza massima sottosequenza comune: %d" % np.max(L))
    
    lcs = ""
    # A partire dall'ultima cella in basso a destra, risaliamo nella tabella seguendo i match avvenuti
    # e recuperando un carattere alla volta la massima sottosequenza comune 
    i = n-1
    j = m-1
    while i > 0 and j > 0: 
        if s[i] == t[j]: # match
            lcs = s[i] + lcs
            i-=1
            j-=1
        elif L[i-1][j] > L[i][j-1]: # Non c'è match in (i,j) e si è arrivati dalla cella sopra (i-1,j)
            i-=1
        else: # Non c'è match e si è arrivati dalla cella a sinistra (i,j-1)
            j-=1
    print "LCS of " + string1 + " and " + string2 + " is " + lcs


# Stringhe iniziali
s = "GAMMAMUOMICRON"
t = "BETAGAMMAPHI"

print("Stringa 1:\t%s" % s)
print("Stringa 2:\t%s" % t)
LCS(s, t)

Stringa 1:	GAMMAMUOMICRON
Stringa 2:	BETAGAMMAPHI
15 13
Tabella L: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 2. 2. 2. 2. 2. 2. 2.]
 [0. 0. 0. 0. 1. 1. 2. 3. 3. 3. 3. 3. 3.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 4. 4. 4. 4.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 5.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 5.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 5.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 5.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 5.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 6.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 6.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 6.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 6.]
 [0. 0. 0. 0. 1. 1. 2. 3. 4. 5. 5. 5. 6.]]
Lunghezza massima sottosequenza comune: 6
LCS of GAMMAMUOMICRON and BETAGAMMAPHI is GAMMAI


In [ ]:
# Esercizio 2 - Campo minato / Percorsi robot

# Questo l'abbiamo visto a esercitazione: provate voi a implementarlo ;)

In [124]:
# Esercizio 3 - Problema dello Zaino

def zaino(pesi, valori, MAX_CAP):
    # Creiamo una matrice n x (MAX_CAP+1) per salvare i risultati dei sottoproblemi
    n = len(pesi)
    S = [[0 for j in range(MAX_CAP+1)] for i in range(n)] # Modo 2 per inizializzare una matrice di tutti zeri
    #print S
    
    for i in range(1,n): # i è l'elemento i-esimo dell'insieme di oggetti disponibili
        for j in range(MAX_CAP+1): # j è la capacità dello zaino
            S[i][j] = S[i-1][j]
            # Assumiamo che il valore massimo della soluzione di V[i, j] sia almeno il valore di V[i-1][j]
            # cioè il sottoproblema con lo zaino avente la stessa capacità e il sottoinsieme di elementi da 1 a i-1
            # A ogni sottoproblema, ci chiediamo se possiamo inserire l'elemento: se sì, perché il peso lo consente,
            # sarebbe conveniente farlo oppure meglio non inserirlo proprio?
            if pesi[i] <= j and S[i-1][j-pesi[i]] + valori[i] > S[i][j]:
                S[i][j] = S[i-1][j-pesi[i]] + valori[i]
    return S

n = 5
MAX_CAP = np.random.randint(30, 50)
m = MAX_CAP
pesi = [0] + list(np.random.randint(0, 10, n)) # così pesi e valori contengono già l'elemento nullo
valori = [0] + list(np.random.randint(0, 100, n))
print "Pesi = " + str(pesi)
print "Valori = " + str(valori)
print "\nValore zaino con n = " + str(n) + " oggetti e capacità " + str(MAX_CAP) + ":\n" + str(zaino(pesi, valori, MAX_CAP)[n][m])

Pesi = [0, 7, 9, 6, 8, 2]
Valori = [0, 19, 40, 32, 44, 75]

Valore zaino con n = 5 oggetti e capacità 42:
210


In [165]:
# Esercizio 4 - Sottosequenza (contigua) con massima somma

# Data una sequenza di numeri reali, individuare la sottosequenza di elementi contigui per cui la loro somma sia massima.
# Esempi:
# L1 = [3, 12, -3, -7, 12, 4, -32, 20, 5, -10, 10] --> S1 = [20, 5] con somma 25
# L2 = [22, -10, 45, -8, 2] --> S2 = [22, -10, 45] con somma 57

# Questo NON l'abbiamo visto a esercitazione:
# provate voi sia a trovare la ricorrenza sia a implementarlo ;)

In [ ]:
# Esercizio 5 - La dieta di Poldo

# Il dottore ordina a Poldo di seguire una dieta. Ad ogni pasto non può mai mangiare un panino che abbia
# un peso maggiore o uguale a quello appena mangiato. Quando Poldo passeggia per la via del suo paese,
# da ogni ristorante esce un cameriere proponendo il menù del giorno. Ciascun menù è composto da una serie di panini,
# che verranno serviti in un ordine ben definito, e dal peso di ciascun panino. Poldo, per non violare la regola della
# sua dieta, una volta scelto un menù, può decidere di mangiare o rifiutare un panino; se lo rifiuta il cameriere
# gli servirà il successivo e quello rifiutato non gli sarà più servito.
# Si deve scrivere un programma che permetta a Poldo, leggendo un menù, di capire qual è il numero massimo di panini
# che può mangiare per quel menù senza violare la regola della sua dieta.
# Riassumendo, Poldo può mangiare un panino se e solo se soddisfa una delle due condizioni:
# - Il panino è il primo che mangia in un determinato pasto;
# - Il panino non ha un peso maggiore o uguale all’ultimo panino che ha mangiato in un determinato pasto.

# Esempio:
# L = [5, 3, 6, 7, 5, 3] --> Numero panini che può mangiare Poldo: 3, con [6, 5, 3] oppure [7, 5, 3]

# Questo NON l'abbiamo visto a esercitazione ed è anche presente sul CMS:
# provate voi sia a trovare la ricorrenza sia a implementarlo ;)